# Generated by Django 5.1 on 2024-11-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sage',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sname',
            new_name='stname',
        ),
        migrations.AlterField(
            model_name='student',
            name='scname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.school'),
        ),
    ]
